

#eureka:
#  client:
#    serviceUrl:
#      register-with-eureka: true
#      fetch-registry: true
#      defaultZone: http://localhost:9001/eureka/eureka
#  instance:
#    preferIpAddress: true
#
#
#spring:
#  profiles:
#    active: dev
#
#---
#spring:
#  profiles: prod
#  application:
#    name: config-eureka-client
#  cloud:
#    config:
#      fail-fast: true
#      discovery:
#        enabled: true
#        service-id: config-jdbc-server
#
#
#---
#spring:
#  profiles: dev
#  application:
#    name: config-eureka-client
#  cloud:
#    config:
#      fail-fast: true
#      discovery:
#        enabled: true  # 开启
#        service-id: config-jdbc-server # 指定配置中心服务端的server-id