spring:
  datasource:
    dynamic:
      primary: master
      hikari:
        max-pool-size: 5
        connection-timeout: 60000
      datasource:
        master:
          username: root
          password:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
          hikari:
            maxPoolSize: 5
            connectionTimeout: 60000
        slave_1:
          username: root
          password:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
          hikari:
            maxPoolSize: 5
            connectionTimeout: 60000